name: Build computer setup script

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Generate bundled PowerShell script
        shell: pwsh
        run: |
          $MergedScriptPath = "./ComputerSetup.ps1"

          $PrerequisitesScript = Get-Content -Path "./Prerequisites.ps1" -Raw
          $EnvironmentScript = Get-Content -Path "./Environment.ps1" -Raw
          $ProgramsScript = Get-Content -Path "./Programs.ps1" -Raw

          $MainScript = (Get-Content -Path "./SetupComputer.ps1") -Replace '\. \.\\Prerequisites\.ps1', $PrerequisitesScript -Replace '\. \.\\Environment\.ps1', $EnvironmentScript -Replace '\. \.\\Programs\.ps1', $ProgramsScript

          Set-Content -Value $MainScript -Path $MergedScriptPath
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: ComputerSetup.ps1