name: Build computer setup script

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Generate bundled PowerShell script
        shell: python
        run: |
          prerequisites_script = open('./Prerequisites.ps1', 'r').read()
          environment_script = open('./Environment.ps1', 'r').read()
          programs_script = open('./Programs.ps1', 'r').read()

          main_script = open('./SetupComputer.ps1', 'r') \
              .read() \
              .replace('. .\\Prerequisites.ps1', prerequisites_script) \
              .replace('. .\\Environment.ps1', environment_script) \
              .replace('. .\\Programs.ps1', programs_script)

          merged_script = open('ComputerSetup.ps1', 'w')
          merged_script.write(main_script)
          merged_script.close()
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: |
            ComputerSetup.ps1
            *.settings.json
          token: ${{ secrets.ACCESS_TOKEN }}