name: Build computer setup script

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Generate bundled PowerShell script
        shell: python
        run: |
          import re

          def replace_script_import(match):
              script_name = match.group(1)
              return import_script('./' + script_name)

          def import_script(script_name):
              script = open(script_name, 'r').read()
              return re.sub(
                  r'\. \.\\(\S+)',
                  replace_script_import,
                  script
              )

          main_script = import_script('./SetupComputer.ps1')

          merged_script = open('ComputerSetup.ps1', 'w')
          merged_script.write(main_script)
          merged_script.close()
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: |
            ComputerSetup.ps1
            windows-terminal/windows-terminal.settings.json
            vscode/vscode.settings.json
            oh-my-posh/theme.omp.json
            neovim/*.lua
            firefox/userChrome.css
          token: ${{ secrets.ACCESS_TOKEN }}